# Generated by Django 5.2.17 on 2026-08-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='variable',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='variable',
            name='leading_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='variable',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
