# Generated by Django 5.2.17 on 2026-08-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_variable_options_variable_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='group_flank_char',
            field=models.CharField(default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='variable',
            name='group_flank_len',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
